config/routes.rb
Rails.application.routes.draw do
  resources :shift_dates
  resources :user_tasks
  resources :user_shifts
  resources :task_shifts
  resources :active_nights
  resources :allnights
  resources :active_times
  resources :shift_times
  resources :desired_tasks
  resources :experience_tasks
  resources :tasks
  resources :user_stations
  resources :stations
  resources :driver_licenses
  resources :affiliations
  resources :committees
  resources :home, :only => [ :index ]
  get 'shift' => 'home#show'
  get 'shift/:id' => 'home#show'
  get 'profile' => 'users#show'
  get 'profile/edit' => 'users#edit'
  put 'profile/edit' => 'users#update'
  patch 'profile/edit' => 'users#update'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :questionnaires, :only => [ :index ]

  get 'managements' => 'managements#index'

  root 'home#index'

end

app/models/active_night.rb
class ActiveNight < ActiveRecord::Base
  belongs_to :user
  belongs_to :allnight
end

app/models/active_time.rb
class ActiveTime < ActiveRecord::Base
  belongs_to :user
  belongs_to :shift_time
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/affiliation.rb
class Affiliation < ActiveRecord::Base
  belongs_to :user
  belongs_to :committee
end

app/models/allnight.rb
class Allnight < ActiveRecord::Base
  has_many :active_nights
  has_many :users, :through => :active_nights
end

app/models/committee.rb
class Committee < ActiveRecord::Base
  has_many :affiliations
  has_many :users, :through => :affiliations
  has_many :stations
end

app/models/desired_task.rb
class DesiredTask < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
end

app/models/driver_license.rb
class DriverLicense < ActiveRecord::Base
  has_many :users
end

app/models/experience_task.rb
class ExperienceTask < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
end

app/models/shift_date.rb
class ShiftDate < ActiveRecord::Base
  has_many :shift_times
end

app/models/shift_time.rb
class ShiftTime < ActiveRecord::Base
  has_many :active_times
  has_many :users, :through => :active_times

  has_many :task_shifts
  has_many :tasks, :through => :task_shifts

  belongs_to :shift_date

  def shift_datetime
      self.shift_date.date.strftime("%Y/%m/%d") + ' ' + self.shift_time.strftime("%H:%M")
  end
  def shift_date_f
    self.shift_date.date.strftime("%Y/%m/%d")
  end
  def shift_time_f
    self.shift_time.strftime("%H:%M")
  end
end

app/models/station.rb
class Station < ActiveRecord::Base
  has_many :user_stations
  has_many :users, :through => :user_stations
  belongs_to :committee
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :experience_tasks
  has_many :users, :through => :experience_tasks

  has_many :desired_tasks
  has_many :users, :through => :desired_tasks

  belongs_to :station

  has_many :task_shifts
  has_many :shift_times, :through => :task_shifts

  has_many :user_tasks
  has_many :users, :through => :user_tasks
end

app/models/task_shift.rb
class TaskShift < ActiveRecord::Base
  belongs_to :task
  belongs_to :shift_time

  has_many :user_shifts
  has_many :users, :through => :user_shifts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :affiliations
  has_many :committees, :through => :affiliations

  belongs_to :driver_license

  has_many :user_stations
  has_many :stations, :through => :user_stations

  has_many :experience_tasks
  has_many :tasks, :through => :experience_tasks

  has_many :desired_tasks
  has_many :tasks, :through => :desired_tasks

  has_many :active_times
  has_many :shift_times, :through => :active_times

  has_many :active_nights
  has_many :allnights, :through => :active_nights

  has_many :user_shifts
  has_many :task_shifts, :through => :user_shifts

  has_many :user_tasks
  has_many :tasks, :through => :user_tasks
end

app/models/user_shift.rb
class UserShift < ActiveRecord::Base
  belongs_to :user
  belongs_to :task_shift

  attr_accessor :assigned
end

app/models/user_station.rb
class UserStation < ActiveRecord::Base
  belongs_to :user
  belongs_to :station
end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
end

app/controllers/committees_controller.rb
class CommitteesController < InheritedResources::Base

  before_action :check_admin_access

  private

    def committee_params
      params.require(:committee).permit(:name)
    end
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/committees/_form.html.erb
<%= form_for @committee, :html => { :class => "form-horizontal committee" } do |f| %>

  <% if @committee.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@committee.errors.count, "error") %> prohibited this committee from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @committee.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                committees_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/committees/edit.html.erb
<%- model_class = Committee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/committees/index.html.erb
<%- model_class = Committee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @committees.each do |committee| %>
      <tr>
        <td><%= link_to committee.id, committee_path(committee) %></td>
        <td><%= committee.name %></td>
        <td><%=l committee.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_committee_path(committee), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      committee_path(committee),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_committee_path,
            :class => 'btn btn-primary' %>

app/views/committees/new.html.erb
<%- model_class = Committee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/committees/show.html.erb
<%- model_class = Committee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @committee.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              committees_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_committee_path(@committee), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              committee_path(@committee),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>